### ISSUE TITLE
Staking calculator doesn't update

### ISSUE THREAD

**Issue by rooster117** [wise-foundation/wise-website-bug-reports#41] opened 2021-04-25 15:59 UTC
**Describe the bug**
Staking calculator doesn't work to change values.

**To Reproduce**
1. Go to home page
2. Click on "Calculate Staking Rewards"
3. Try to change coin type or staking length and selection does not update

**Expected behavior**
The values should update

**Screenshots**
<img width="1081" alt="Screen Shot 2021-04-25 at 8 58 40 AM" src="https://user-images.githubusercontent.com/1245401/116000292-7325aa80-a5a4-11eb-908d-02e0ff1471a0.png">

**Desktop (please complete the following information):**
osx
Chrome or Safari

**Comment by coffee-converter** [comment] 2021-04-25 16:33
Seems to work fine here:

![1](https://user-images.githubusercontent.com/61335667/116001423-fbfb1100-a5b9-11eb-8f1a-ecd0d4e1b531.png)
![2](https://user-images.githubusercontent.com/61335667/116001426-fdc4d480-a5b9-11eb-9bc6-e7cfbcb52378.png)
![3](https://user-images.githubusercontent.com/61335667/116001427-fef60180-a5b9-11eb-9f36-baa7acb9611f.png)

**Comment by coffee-converter** [comment] 2021-04-27 17:18
Seems fine, I'm unable to reproduce the issue.  Closing for now.  If you can find a consistent way to reproduce it, please reopen.  Thanks.

**Closed as completed by coffee-converter** 2021-04-27 17:18 UTC
Labels: bug
